### ISSUE TITLE
扫码导入ga后手机黑屏，导出日志也会黑屏

### ISSUE THREAD

**Issue by pugaizai** [Robert-Stackflow/CloudOTP#9]
**Describe the bug**
扫码导入ga后手机黑屏，导出日志也会导致黑屏，此时手机触摸屏没法用，只能重启。

**Smartphone (please complete the following information):**
 - Device: vivo y76s
 - OS: 安卓 11

```
2024-09-08 01:44:46:615
Database not exist and new password is 
2024-09-08 01:44:46:629
Configure database with cipher successfully. Result is [{ok: ok}]
2024-09-08 01:44:47:751
Current version: 2.4.0, Latest version: 2.4.0
2024-09-08 01:44:52:722
Current version: 2.4.0, Latest version: 2.4.0
2024-09-08 01:45:02:593
Current version: 2.4.0, Latest version: 2.4.0
2024-09-08 01:45:05:107
Current version: 2.4.0, Latest version: 2.4.0
2024-09-08 01:46:57:734
Current version: 2.4.0, Latest version: 2.4.0
2024-09-08 01:48:31:406
Current version: 2.4.0, Latest version: 2.4.0
2024-09-08 01:49:16:083
Current version: 2.4.0, Latest version: 2.4.0
2024-09-08 01:55:42:238
Current version: 2.4.0, Latest version: 2.4.0
2024-09-08 01:55:45:141
Current version: 2.4.0, Latest version: 2.4.0
2024-09-08 01:55:47:474
Current version: 2.4.0, Latest version: 2.4.0
2024-09-08 01:56:41:196
Current version: 2.4.0, Latest version: 2.4.0
ReaderException
#0   Detector._computeDimension (package:zxing2/src/qrcode/detector/detector.dart:174)
#1   Detector.processFinderPatternInfo (package:zxing2/src/qrcode/detector/detector.dart:57)
#2   Detector.detect (package:zxing2/src/qrcode/detector/detector.dart:44)
#3   QRCodeReader.decode (package:zxing2/src/qrcode/qrcode_reader.dart:40)
#4   ImportTokenUtil.analyzeImage.<anonymous closure> (package:cloudotp/TokenUtils/import_token_util.dart:207)
#5   compute.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:19)
#6   _RemoteRunner._run (dart:isolate:1098)
#7   _RemoteRunner._remoteExecute (dart:isolate:1092)
#8   _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300)
#9   _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
2024-09-08 01:59:46:477
Failed to analyze image
2024-09-08 02:02:36:174
Database is an encrypted SQLite database.
2024-09-08 02:02:36:199
Configure database with cipher successfully. Result is [{ok: ok}]
2024-09-08 02:02:37:687
Current version: 2.4.0, Latest version: 2.4.0
ReaderException
#0   Detector._computeDimension (package:zxing2/src/qrcode/detector/detector.dart:174)
#1   Detector.processFinderPatternInfo (package:zxing2/src/qrcode/detector/detector.dart:57)
#2   Detector.detect (package:zxing2/src/qrcode/detector/detector.dart:44)
#3   QRCodeReader.decode (package:zxing2/src/qrcode/qrcode_reader.dart:40)
#4   ImportTokenUtil.analyzeImage.<anonymous closure> (package:cloudotp/TokenUtils/import_token_util.dart:207)
#5   compute.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:19)
#6   _RemoteRunner._run (dart:isolate:1098)
#7   _RemoteRunner._remoteExecute (dart:isolate:1092)
#8   _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300)
#9   _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
2024-09-08 02:03:12:440
Failed to analyze image
2024-09-08 02:04:55:080
Database is an encrypted SQLite database.
2024-09-08 02:04:55:100
Configure database with cipher successfully. Result is [{ok: ok}]
2024-09-08 02:04:56:561
Current version: 2.4.0, Latest version: 2.4.0
2024-09-08 02:05:03:142
Current version: 2.4.0, Latest version: 2.4.0

```

**Comment by Robert-Stackflow** [comment]
点击导出日志后立即黑屏吗？是直接卡死了？

**Comment by pugaizai** [comment]
> 点击导出日志后立即黑屏吗？是直接卡死了？

232版本导出日志也没问题

**Comment by Robert-Stackflow** [comment]
2.3.2版本扫描导入google authenticator有问题吗

**Comment by pugaizai** [comment]
> 2.3.2版本扫描导入google authenticator有问题吗

没有问题，但是导入不全 github google twitter 什么的都没导入

**Comment by Robert-Stackflow** [comment]
> > 2.3.2版本扫描导入google authenticator有问题吗
> 
> 没有问题，但是导入不全 github google twitter 什么的都没导入。上面那个日志应该是我ga导出的时候截错二维码了应该可以无视

我这边测试导入没问题，你到2.4.2版本看看

**Comment by pugaizai** [comment]
> > > 2.3.2版本扫描导入google authenticator有问题吗
> > 
> > 
> > 没有问题，但是导入不全 github google twitter 什么的都没导入。上面那个日志应该是我ga导出的时候截错二维码了应该可以无视
> 
> 我这边测试导入没问题，你到2.4.2版本看看

ok了
